FROM ubuntu:20.04

ENV NAME=ubuntu-toolbox VERSION=20.04
LABEL com.github.containers.toolbox="true"

COPY README.md /

COPY missing-docs /
RUN DEBIAN_FRONTEND=noninteractive apt-get update -qy && DEBIAN_FRONTEND=noninteractive xargs -a missing-docs apt-get -qy install
RUN rm /missing-docs

COPY extra-packages /
RUN DEBIAN_FRONTEND=noninteractive apt-get update -qy && DEBIAN_FRONTEND=noninteractive xargs -a extra-packages apt-get -qy install
RUN rm /extra-packages

COPY nsswitch.conf /etc/nsswitch.conf

RUN apt-get -y clean
