FROM archlinux

ENV NAME=archlinux-toolbox VERSION=latest
LABEL com.github.containers.toolbox="true"

COPY README.md /

RUN pacman --noconfirm -Syu

COPY missing-docs /
RUN pacman --noconfirm -Syu $(<missing-docs)
RUN rm /missing-docs

COPY extra-packages /
RUN pacman --noconfirm -Syu $(<extra-packages)
RUN rm /extra-packages

RUN pacman --noconfirm -Scc

RUN echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/toolbox
