name: build toolbox container images

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


env:
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
  TOOLBOX_REPO: ghcr.io/${{ github.repository_owner }}/toolbox-images

jobs:
  publish-all:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to ghcr.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}
        registry: ${{ env.TOOLBOX_REPO }}

    - name: publish toolbox container images
      run: ./util/publish.sh ubuntu/22.04
